name: json_fields_example
description: An example of how to use json_fields

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  json_annotation: ^4.1.0

dev_dependencies:
  json_serializable: ^5.0.2
  build_runner: ^2.1.4
  json_fields:
    path: ../

scripts: ../derry.yaml
